### ISSUE TITLE
Throttle and brake have negative values

### ISSUE THREAD

**Issue by borisdayma** [borisd13/CarND-Capstone#17]
Throttle and brake have sometimes negative values, which should not be possible.

**Comment by taikione** [comment]
You can change minimum output value of PID. Please check [this launch file](https://github.com/borisd13/CarND-Capstone/blob/master/ros/src/twist_controller/launch/dbw_sim.launch#L7).

**Comment by borisdayma** [comment]
I think "decel_limit" is related to max brake. But the min of throttle and brake should probably be 0, meaning that they are not engaged at all.
So we would have:
- throttle needs to be between 0 and accel_limit
- brake needs to be between 0 and -decel_limit
What do you think?

**Comment by taikione** [comment]
I entirely agree with you.

This is nice!
> brake needs to be between 0 and -decel_limit
