### ISSUE TITLE
Throttle is often at 1 (fully engaged)

### ISSUE THREAD

**Issue by borisdayma** [borisd13/CarND-Capstone#18]
Throttle is often at 1, meaning fully engaged. This should be avoided and limited to a lower value as it creates a too aggressive behavior on Carla based on feedback of testers.

**Comment by chris-ferone** [comment]
With the car ignoring traffic lights, the only time I see the throttle at 1 is when the car accelerates from a stop. Once the car reaches its speed setpoint, the throttle settles to around 0.22. So I'm not sure its accurate to say the throttle is "often" at 1. 

If full throttle (1) is discouraged under any circumstance, then a simple solution is to saturate the the throttle at a lower value (i.e. 0.5). This will result in slower accelerations, but will be more comfortable to the driver and passengers. Where did you hear that a throttle of 1 was too aggressive?
