### ISSUE TITLE
Traffic light detection

### ISSUE THREAD

**Issue by borisdayma** [borisd13/CarND-Capstone#3]
Detection: Detect the traffic light and its color from the /image_color. The topic /vehicle/traffic_lights contains the exact location and status of all traffic lights in simulator, so you can test your output.

**Comment by taikione** [comment]
I have implemented code to train model !!! (these scripts works only tensorflow 1.3.0.)
https://github.com/taikione/CarND-Capstone/tree/train_model/ros/src/tl_detector/light_classification/train_model

Trained model is [here](https://drive.google.com/file/d/1tOduTs8vYKK1B4MFGkPMBz-QlzSrzLgl/view?usp=sharing). but I have not tried it with the simulator yet.

**Comment by taikione** [comment]
I had implemented prediction on simulator. (but it's so laggy...) I think reduce the number of layers in model. please comment something if you have advice.

https://github.com/taikione/CarND-Capstone/commit/5b73f267a6cce94645eca36f993db8fbfb905240

**Comment by borisdayma** [comment]
I think the model is too big. Let's target very small and fast models (below 50Mo). I'm trying on my side as well so will let you know if I get something working.

**Comment by taikione** [comment]
I have implemented code that vehicle speed change by traffic light. but, this is need adjustment to vehicle stop position.

https://github.com/taikione/CarND-Capstone/tree/update_wp_updater

**Comment by borisdayma** [comment]
This has now been completed in master branch
